Show segfault with write function
dshafik/php-http2-push-example pull request #3
Opened 2018-07-24 20:49 UTC by Nyholm

▶  php blog-example.php
Write[1]    44542 segmentation fault  php blog-example.php

2019-02-21 21:28 UTC, airzaza51 approved these changes

2019-02-21 21:28 UTC, airzaza51 commented
..

2019-02-21 21:33 UTC, airzaza51 requested changes
ขอความเมตตา

2019-02-26 18:32 UTC, Nyholm commented
This is solved in php-master

2019-02-26 18:32 UTC, closed without merging